// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "ScreenshotApi.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

NSObject<FlutterMessageCodec> *FLTScreenshotHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void FLTScreenshotHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTScreenshotHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ff_native_screenshot.ScreenshotHostApi.takeScreenshot"
        binaryMessenger:binaryMessenger
        codec:FLTScreenshotHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(takeScreenshotWithCompletion:)], @"FLTScreenshotHostApi api (%@) doesn't respond to @selector(takeScreenshotWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api takeScreenshotWithCompletion:^(FlutterStandardTypedData *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ff_native_screenshot.ScreenshotHostApi.startListeningScreenshot"
        binaryMessenger:binaryMessenger
        codec:FLTScreenshotHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startListeningScreenshotWithError:)], @"FLTScreenshotHostApi api (%@) doesn't respond to @selector(startListeningScreenshotWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api startListeningScreenshotWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ff_native_screenshot.ScreenshotHostApi.stopListeningScreenshot"
        binaryMessenger:binaryMessenger
        codec:FLTScreenshotHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopListeningScreenshotWithError:)], @"FLTScreenshotHostApi api (%@) doesn't respond to @selector(stopListeningScreenshotWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api stopListeningScreenshotWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
NSObject<FlutterMessageCodec> *FLTScreenshotFlutterApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

@interface FLTScreenshotFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation FLTScreenshotFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onTakeScreenshotData:(nullable FlutterStandardTypedData *)arg_data completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.ff_native_screenshot.ScreenshotFlutterApi.onTakeScreenshot"
      binaryMessenger:self.binaryMessenger
      codec:FLTScreenshotFlutterApiGetCodec()];
  [channel sendMessage:@[arg_data ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
@end

