// Autogenerated from Pigeon (v3.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FLTScreenshotHostApi.
NSObject<FlutterMessageCodec> *FLTScreenshotHostApiGetCodec(void);

@protocol FLTScreenshotHostApi
- (void)takeScreenshotWithCompletion:(void(^)(FlutterStandardTypedData *_Nullable, FlutterError *_Nullable))completion;
- (void)startListeningScreenshotWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopListeningScreenshotWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTScreenshotHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTScreenshotHostApi> *_Nullable api);

/// The codec used by FLTScreenshotFlutterApi.
NSObject<FlutterMessageCodec> *FLTScreenshotFlutterApiGetCodec(void);

@interface FLTScreenshotFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onTakeScreenshotData:(nullable FlutterStandardTypedData *)data completion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
