// Autogenerated from Pigeon (v3.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "ScreenshotApi.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}



@interface FLTFlutterScreenshotApiCodecReader : FlutterStandardReader
@end
@implementation FLTFlutterScreenshotApiCodecReader
@end

@interface FLTFlutterScreenshotApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTFlutterScreenshotApiCodecWriter
@end

@interface FLTFlutterScreenshotApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTFlutterScreenshotApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTFlutterScreenshotApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTFlutterScreenshotApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTFlutterScreenshotApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    FLTFlutterScreenshotApiCodecReaderWriter *readerWriter = [[FLTFlutterScreenshotApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void FLTFlutterScreenshotApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTFlutterScreenshotApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FlutterScreenshotApi.takeScreenshot"
        binaryMessenger:binaryMessenger
        codec:FLTFlutterScreenshotApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(takeScreenshotWithCompletion:)], @"FLTFlutterScreenshotApi api (%@) doesn't respond to @selector(takeScreenshotWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api takeScreenshotWithCompletion:^(FlutterStandardTypedData *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FlutterScreenshotApi.startListeningScreenshot"
        binaryMessenger:binaryMessenger
        codec:FLTFlutterScreenshotApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startListeningScreenshotWithError:)], @"FLTFlutterScreenshotApi api (%@) doesn't respond to @selector(startListeningScreenshotWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api startListeningScreenshotWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FlutterScreenshotApi.stopListeningScreenshot"
        binaryMessenger:binaryMessenger
        codec:FLTFlutterScreenshotApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopListeningScreenshotWithError:)], @"FLTFlutterScreenshotApi api (%@) doesn't respond to @selector(stopListeningScreenshotWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api stopListeningScreenshotWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FLTNativeScreenshotApiCodecReader : FlutterStandardReader
@end
@implementation FLTNativeScreenshotApiCodecReader
@end

@interface FLTNativeScreenshotApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTNativeScreenshotApiCodecWriter
@end

@interface FLTNativeScreenshotApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTNativeScreenshotApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTNativeScreenshotApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTNativeScreenshotApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTNativeScreenshotApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    FLTNativeScreenshotApiCodecReaderWriter *readerWriter = [[FLTNativeScreenshotApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


@interface FLTNativeScreenshotApi ()
@property (nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation FLTNativeScreenshotApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onTakeScreenshotData:(nullable FlutterStandardTypedData *)arg_data completion:(void(^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.NativeScreenshotApi.onTakeScreenshot"
      binaryMessenger:self.binaryMessenger
      codec:FLTNativeScreenshotApiGetCodec()];
  [channel sendMessage:@[arg_data ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
@end
